<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\quran-data.js" LogicalName="quran-data.js" />
    <EmbeddedResource Include="Data\inspirasi.json" LogicalName="inspirasi.json" />
    <EmbeddedResource Include="Data\madinah-text.json" LogicalName="madinah-text.json" />
    <EmbeddedResource Include="Resources\UthmanicHafs.ttf" LogicalName="UthmanicHafs.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.2" />
    <PackageReference Include="SoundTouch.Net" Version="2.3.2" />
    <PackageReference Include="System.Speech" Version="10.0.11" />
  </ItemGroup>

</Project>